// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fairblock/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSubmitEncrypted struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	MessageHash  string `protobuf:"bytes,2,opt,name=messageHash,proto3" json:"messageHash,omitempty"`
	Encryption   string `protobuf:"bytes,3,opt,name=encryption,proto3" json:"encryption,omitempty"`
	TargetHeight string `protobuf:"bytes,4,opt,name=targetHeight,proto3" json:"targetHeight,omitempty"`
	Deposit      string `protobuf:"bytes,5,opt,name=deposit,proto3" json:"deposit,omitempty"`
}

func (m *MsgSubmitEncrypted) Reset()         { *m = MsgSubmitEncrypted{} }
func (m *MsgSubmitEncrypted) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitEncrypted) ProtoMessage()    {}
func (*MsgSubmitEncrypted) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0a1902eeba049d, []int{0}
}
func (m *MsgSubmitEncrypted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitEncrypted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitEncrypted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitEncrypted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitEncrypted.Merge(m, src)
}
func (m *MsgSubmitEncrypted) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitEncrypted) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitEncrypted.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitEncrypted proto.InternalMessageInfo

func (m *MsgSubmitEncrypted) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitEncrypted) GetMessageHash() string {
	if m != nil {
		return m.MessageHash
	}
	return ""
}

func (m *MsgSubmitEncrypted) GetEncryption() string {
	if m != nil {
		return m.Encryption
	}
	return ""
}

func (m *MsgSubmitEncrypted) GetTargetHeight() string {
	if m != nil {
		return m.TargetHeight
	}
	return ""
}

func (m *MsgSubmitEncrypted) GetDeposit() string {
	if m != nil {
		return m.Deposit
	}
	return ""
}

type MsgSubmitEncryptedResponse struct {
}

func (m *MsgSubmitEncryptedResponse) Reset()         { *m = MsgSubmitEncryptedResponse{} }
func (m *MsgSubmitEncryptedResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitEncryptedResponse) ProtoMessage()    {}
func (*MsgSubmitEncryptedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0a1902eeba049d, []int{1}
}
func (m *MsgSubmitEncryptedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitEncryptedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitEncryptedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitEncryptedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitEncryptedResponse.Merge(m, src)
}
func (m *MsgSubmitEncryptedResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitEncryptedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitEncryptedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitEncryptedResponse proto.InternalMessageInfo

type MsgCommitDecryption struct {
	Creator                string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PlaintextHash          string `protobuf:"bytes,2,opt,name=plaintextHash,proto3" json:"plaintextHash,omitempty"`
	PlaintextDecryptorHash string `protobuf:"bytes,3,opt,name=plaintextDecryptorHash,proto3" json:"plaintextDecryptorHash,omitempty"`
}

func (m *MsgCommitDecryption) Reset()         { *m = MsgCommitDecryption{} }
func (m *MsgCommitDecryption) String() string { return proto.CompactTextString(m) }
func (*MsgCommitDecryption) ProtoMessage()    {}
func (*MsgCommitDecryption) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0a1902eeba049d, []int{2}
}
func (m *MsgCommitDecryption) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCommitDecryption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCommitDecryption.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCommitDecryption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCommitDecryption.Merge(m, src)
}
func (m *MsgCommitDecryption) XXX_Size() int {
	return m.Size()
}
func (m *MsgCommitDecryption) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCommitDecryption.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCommitDecryption proto.InternalMessageInfo

func (m *MsgCommitDecryption) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCommitDecryption) GetPlaintextHash() string {
	if m != nil {
		return m.PlaintextHash
	}
	return ""
}

func (m *MsgCommitDecryption) GetPlaintextDecryptorHash() string {
	if m != nil {
		return m.PlaintextDecryptorHash
	}
	return ""
}

type MsgCommitDecryptionResponse struct {
}

func (m *MsgCommitDecryptionResponse) Reset()         { *m = MsgCommitDecryptionResponse{} }
func (m *MsgCommitDecryptionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCommitDecryptionResponse) ProtoMessage()    {}
func (*MsgCommitDecryptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0a1902eeba049d, []int{3}
}
func (m *MsgCommitDecryptionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCommitDecryptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCommitDecryptionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCommitDecryptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCommitDecryptionResponse.Merge(m, src)
}
func (m *MsgCommitDecryptionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCommitDecryptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCommitDecryptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCommitDecryptionResponse proto.InternalMessageInfo

type MsgRevealDecryption struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Plaintext string `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
}

func (m *MsgRevealDecryption) Reset()         { *m = MsgRevealDecryption{} }
func (m *MsgRevealDecryption) String() string { return proto.CompactTextString(m) }
func (*MsgRevealDecryption) ProtoMessage()    {}
func (*MsgRevealDecryption) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0a1902eeba049d, []int{4}
}
func (m *MsgRevealDecryption) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevealDecryption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRevealDecryption.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRevealDecryption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevealDecryption.Merge(m, src)
}
func (m *MsgRevealDecryption) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevealDecryption) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevealDecryption.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevealDecryption proto.InternalMessageInfo

func (m *MsgRevealDecryption) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRevealDecryption) GetPlaintext() string {
	if m != nil {
		return m.Plaintext
	}
	return ""
}

type MsgRevealDecryptionResponse struct {
}

func (m *MsgRevealDecryptionResponse) Reset()         { *m = MsgRevealDecryptionResponse{} }
func (m *MsgRevealDecryptionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRevealDecryptionResponse) ProtoMessage()    {}
func (*MsgRevealDecryptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0a1902eeba049d, []int{5}
}
func (m *MsgRevealDecryptionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevealDecryptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRevealDecryptionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRevealDecryptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevealDecryptionResponse.Merge(m, src)
}
func (m *MsgRevealDecryptionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevealDecryptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevealDecryptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevealDecryptionResponse proto.InternalMessageInfo

type MsgSubmitShare struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	KeyShare     string `protobuf:"bytes,2,opt,name=keyShare,proto3" json:"keyShare,omitempty"`
	TargetHeight string `protobuf:"bytes,3,opt,name=targetHeight,proto3" json:"targetHeight,omitempty"`
}

func (m *MsgSubmitShare) Reset()         { *m = MsgSubmitShare{} }
func (m *MsgSubmitShare) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitShare) ProtoMessage()    {}
func (*MsgSubmitShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0a1902eeba049d, []int{6}
}
func (m *MsgSubmitShare) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitShare.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitShare.Merge(m, src)
}
func (m *MsgSubmitShare) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitShare) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitShare.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitShare proto.InternalMessageInfo

func (m *MsgSubmitShare) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitShare) GetKeyShare() string {
	if m != nil {
		return m.KeyShare
	}
	return ""
}

func (m *MsgSubmitShare) GetTargetHeight() string {
	if m != nil {
		return m.TargetHeight
	}
	return ""
}

type MsgSubmitShareResponse struct {
}

func (m *MsgSubmitShareResponse) Reset()         { *m = MsgSubmitShareResponse{} }
func (m *MsgSubmitShareResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitShareResponse) ProtoMessage()    {}
func (*MsgSubmitShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0a1902eeba049d, []int{7}
}
func (m *MsgSubmitShareResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitShareResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitShareResponse.Merge(m, src)
}
func (m *MsgSubmitShareResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitShareResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSubmitEncrypted)(nil), "pememoni.fairblock.fairblock.MsgSubmitEncrypted")
	proto.RegisterType((*MsgSubmitEncryptedResponse)(nil), "pememoni.fairblock.fairblock.MsgSubmitEncryptedResponse")
	proto.RegisterType((*MsgCommitDecryption)(nil), "pememoni.fairblock.fairblock.MsgCommitDecryption")
	proto.RegisterType((*MsgCommitDecryptionResponse)(nil), "pememoni.fairblock.fairblock.MsgCommitDecryptionResponse")
	proto.RegisterType((*MsgRevealDecryption)(nil), "pememoni.fairblock.fairblock.MsgRevealDecryption")
	proto.RegisterType((*MsgRevealDecryptionResponse)(nil), "pememoni.fairblock.fairblock.MsgRevealDecryptionResponse")
	proto.RegisterType((*MsgSubmitShare)(nil), "pememoni.fairblock.fairblock.MsgSubmitShare")
	proto.RegisterType((*MsgSubmitShareResponse)(nil), "pememoni.fairblock.fairblock.MsgSubmitShareResponse")
}

func init() { proto.RegisterFile("fairblock/tx.proto", fileDescriptor_ad0a1902eeba049d) }

var fileDescriptor_ad0a1902eeba049d = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0xce, 0x12, 0x5e, 0x9d, 0xf2, 0xd2, 0x22, 0x55, 0x96, 0x09, 0x56, 0x65, 0x71, 0xe0, 0x80,
	0x6c, 0x5e, 0x42, 0x70, 0x2d, 0x0f, 0x95, 0x83, 0x2f, 0xe9, 0x8d, 0xdb, 0xda, 0x1d, 0xec, 0xa5,
	0xb1, 0xd7, 0xec, 0x6e, 0x51, 0x72, 0x40, 0xe2, 0x0f, 0x20, 0xf1, 0x4b, 0xf8, 0x1d, 0x1c, 0x7b,
	0xe4, 0x88, 0x92, 0xdf, 0x81, 0x84, 0xd8, 0xd8, 0x5b, 0x3f, 0x9a, 0x36, 0xb9, 0x79, 0xbf, 0xf9,
	0x66, 0xbe, 0x6f, 0x3c, 0xa3, 0x01, 0xfa, 0x91, 0x71, 0x19, 0x4f, 0x44, 0x72, 0x14, 0xea, 0x69,
	0x50, 0x4a, 0xa1, 0x05, 0x1d, 0x95, 0x98, 0x63, 0x2e, 0x0a, 0x1e, 0xd8, 0xe0, 0xe9, 0x97, 0xff,
	0x93, 0x00, 0x8d, 0x54, 0x7a, 0x70, 0x1c, 0xe7, 0x5c, 0xbf, 0x2d, 0x12, 0x39, 0x2b, 0x35, 0x1e,
	0x52, 0x07, 0xae, 0x25, 0x12, 0x99, 0x16, 0xd2, 0x21, 0xbb, 0xe4, 0xe1, 0xd6, 0xb8, 0x7e, 0xd2,
	0x5d, 0xd8, 0xce, 0x51, 0x29, 0x96, 0xe2, 0x3e, 0x53, 0x99, 0x73, 0xc9, 0x44, 0x9b, 0x10, 0xf5,
	0x00, 0x70, 0x59, 0x88, 0x8b, 0xc2, 0x19, 0x1a, 0x42, 0x03, 0xa1, 0x3e, 0xdc, 0xd0, 0x4c, 0xa6,
	0xa8, 0xf7, 0x91, 0xa7, 0x99, 0x76, 0x2e, 0x1b, 0x46, 0x0b, 0xfb, 0xaf, 0x7f, 0x88, 0xa5, 0x50,
	0x5c, 0x3b, 0x57, 0x96, 0xfa, 0xd5, 0xd3, 0x1f, 0x81, 0xdb, 0xf7, 0x3b, 0x46, 0x55, 0x8a, 0x42,
	0xa1, 0xff, 0x9d, 0xc0, 0xdd, 0x48, 0xa5, 0xaf, 0x45, 0x9e, 0x73, 0xfd, 0x06, 0xad, 0xe6, 0xea,
	0x7e, 0x1e, 0xc0, 0xcd, 0x72, 0xc2, 0x78, 0xa1, 0x71, 0xaa, 0x1b, 0x1d, 0xb5, 0x41, 0xfa, 0x02,
	0x76, 0x2c, 0x50, 0x95, 0x15, 0xd2, 0xd0, 0x97, 0xfd, 0xad, 0x88, 0xfa, 0xf7, 0xe1, 0xde, 0x19,
	0x76, 0xac, 0xdd, 0xc8, 0xb8, 0x1d, 0xe3, 0x17, 0x64, 0x93, 0xb5, 0xdc, 0x8e, 0x60, 0xcb, 0x2a,
	0x55, 0x4e, 0x4f, 0x81, 0x4a, 0xad, 0x5b, 0xce, 0xaa, 0x7d, 0x82, 0x5b, 0xf6, 0xd7, 0x1d, 0x64,
	0x4c, 0xe2, 0x39, 0x42, 0x2e, 0x5c, 0x3f, 0xc2, 0x99, 0x61, 0x55, 0x3a, 0xf6, 0xdd, 0x1b, 0xe0,
	0xb0, 0x3f, 0x40, 0xdf, 0x81, 0x9d, 0xb6, 0x56, 0xed, 0xe2, 0xe9, 0xdf, 0x21, 0x0c, 0x23, 0x95,
	0xd2, 0xaf, 0x70, 0xbb, 0xbb, 0x75, 0x8f, 0x83, 0xf3, 0x76, 0x35, 0xe8, 0xcf, 0xdd, 0x7d, 0xb9,
	0x69, 0x46, 0x6d, 0x83, 0x7e, 0x23, 0x70, 0xa7, 0xb7, 0x26, 0x4f, 0x2e, 0x2c, 0xd7, 0x4d, 0x71,
	0x5f, 0x6d, 0x9c, 0xd2, 0xb2, 0xd0, 0x9b, 0xfd, 0xc5, 0x16, 0xba, 0x29, 0x6b, 0x58, 0x58, 0xb5,
	0x12, 0xf4, 0x33, 0x6c, 0x37, 0xf7, 0xe1, 0xd1, 0x9a, 0xbf, 0xd3, 0xb0, 0xdd, 0xe7, 0x9b, 0xb0,
	0x6b, 0xc9, 0xbd, 0xf7, 0xbf, 0xe6, 0x1e, 0x39, 0x99, 0x7b, 0xe4, 0xcf, 0xdc, 0x23, 0x3f, 0x16,
	0xde, 0xe0, 0x64, 0xe1, 0x0d, 0x7e, 0x2f, 0xbc, 0xc1, 0x87, 0x30, 0xe5, 0x3a, 0x3b, 0x8e, 0x83,
	0x44, 0xe4, 0x61, 0x5d, 0x39, 0x7c, 0xc7, 0xb8, 0xdc, 0x33, 0x17, 0x6d, 0x1a, 0x36, 0xae, 0xdb,
	0xac, 0x44, 0x15, 0x5f, 0x35, 0x17, 0xee, 0xd9, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x17,
	0xdc, 0xfe, 0xf7, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SubmitEncrypted(ctx context.Context, in *MsgSubmitEncrypted, opts ...grpc.CallOption) (*MsgSubmitEncryptedResponse, error)
	CommitDecryption(ctx context.Context, in *MsgCommitDecryption, opts ...grpc.CallOption) (*MsgCommitDecryptionResponse, error)
	RevealDecryption(ctx context.Context, in *MsgRevealDecryption, opts ...grpc.CallOption) (*MsgRevealDecryptionResponse, error)
	SubmitShare(ctx context.Context, in *MsgSubmitShare, opts ...grpc.CallOption) (*MsgSubmitShareResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitEncrypted(ctx context.Context, in *MsgSubmitEncrypted, opts ...grpc.CallOption) (*MsgSubmitEncryptedResponse, error) {
	out := new(MsgSubmitEncryptedResponse)
	err := c.cc.Invoke(ctx, "/pememoni.fairblock.fairblock.Msg/SubmitEncrypted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CommitDecryption(ctx context.Context, in *MsgCommitDecryption, opts ...grpc.CallOption) (*MsgCommitDecryptionResponse, error) {
	out := new(MsgCommitDecryptionResponse)
	err := c.cc.Invoke(ctx, "/pememoni.fairblock.fairblock.Msg/CommitDecryption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevealDecryption(ctx context.Context, in *MsgRevealDecryption, opts ...grpc.CallOption) (*MsgRevealDecryptionResponse, error) {
	out := new(MsgRevealDecryptionResponse)
	err := c.cc.Invoke(ctx, "/pememoni.fairblock.fairblock.Msg/RevealDecryption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitShare(ctx context.Context, in *MsgSubmitShare, opts ...grpc.CallOption) (*MsgSubmitShareResponse, error) {
	out := new(MsgSubmitShareResponse)
	err := c.cc.Invoke(ctx, "/pememoni.fairblock.fairblock.Msg/SubmitShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SubmitEncrypted(context.Context, *MsgSubmitEncrypted) (*MsgSubmitEncryptedResponse, error)
	CommitDecryption(context.Context, *MsgCommitDecryption) (*MsgCommitDecryptionResponse, error)
	RevealDecryption(context.Context, *MsgRevealDecryption) (*MsgRevealDecryptionResponse, error)
	SubmitShare(context.Context, *MsgSubmitShare) (*MsgSubmitShareResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitEncrypted(ctx context.Context, req *MsgSubmitEncrypted) (*MsgSubmitEncryptedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitEncrypted not implemented")
}
func (*UnimplementedMsgServer) CommitDecryption(ctx context.Context, req *MsgCommitDecryption) (*MsgCommitDecryptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitDecryption not implemented")
}
func (*UnimplementedMsgServer) RevealDecryption(ctx context.Context, req *MsgRevealDecryption) (*MsgRevealDecryptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevealDecryption not implemented")
}
func (*UnimplementedMsgServer) SubmitShare(ctx context.Context, req *MsgSubmitShare) (*MsgSubmitShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitShare not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitEncrypted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitEncrypted)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitEncrypted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pememoni.fairblock.fairblock.Msg/SubmitEncrypted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitEncrypted(ctx, req.(*MsgSubmitEncrypted))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CommitDecryption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCommitDecryption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CommitDecryption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pememoni.fairblock.fairblock.Msg/CommitDecryption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CommitDecryption(ctx, req.(*MsgCommitDecryption))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevealDecryption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevealDecryption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevealDecryption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pememoni.fairblock.fairblock.Msg/RevealDecryption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevealDecryption(ctx, req.(*MsgRevealDecryption))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitShare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pememoni.fairblock.fairblock.Msg/SubmitShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitShare(ctx, req.(*MsgSubmitShare))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pememoni.fairblock.fairblock.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitEncrypted",
			Handler:    _Msg_SubmitEncrypted_Handler,
		},
		{
			MethodName: "CommitDecryption",
			Handler:    _Msg_CommitDecryption_Handler,
		},
		{
			MethodName: "RevealDecryption",
			Handler:    _Msg_RevealDecryption_Handler,
		},
		{
			MethodName: "SubmitShare",
			Handler:    _Msg_SubmitShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fairblock/tx.proto",
}

func (m *MsgSubmitEncrypted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitEncrypted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitEncrypted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Deposit) > 0 {
		i -= len(m.Deposit)
		copy(dAtA[i:], m.Deposit)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Deposit)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TargetHeight) > 0 {
		i -= len(m.TargetHeight)
		copy(dAtA[i:], m.TargetHeight)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TargetHeight)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Encryption) > 0 {
		i -= len(m.Encryption)
		copy(dAtA[i:], m.Encryption)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Encryption)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MessageHash) > 0 {
		i -= len(m.MessageHash)
		copy(dAtA[i:], m.MessageHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MessageHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitEncryptedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitEncryptedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitEncryptedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCommitDecryption) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCommitDecryption) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCommitDecryption) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PlaintextDecryptorHash) > 0 {
		i -= len(m.PlaintextDecryptorHash)
		copy(dAtA[i:], m.PlaintextDecryptorHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PlaintextDecryptorHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PlaintextHash) > 0 {
		i -= len(m.PlaintextHash)
		copy(dAtA[i:], m.PlaintextHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PlaintextHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCommitDecryptionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCommitDecryptionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCommitDecryptionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRevealDecryption) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevealDecryption) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevealDecryption) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Plaintext) > 0 {
		i -= len(m.Plaintext)
		copy(dAtA[i:], m.Plaintext)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Plaintext)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRevealDecryptionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevealDecryptionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevealDecryptionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitShare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitShare) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitShare) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TargetHeight) > 0 {
		i -= len(m.TargetHeight)
		copy(dAtA[i:], m.TargetHeight)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TargetHeight)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.KeyShare) > 0 {
		i -= len(m.KeyShare)
		copy(dAtA[i:], m.KeyShare)
		i = encodeVarintTx(dAtA, i, uint64(len(m.KeyShare)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitShareResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitShareResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitShareResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitEncrypted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MessageHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Encryption)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TargetHeight)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Deposit)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitEncryptedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCommitDecryption) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PlaintextHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PlaintextDecryptorHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCommitDecryptionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRevealDecryption) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Plaintext)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRevealDecryptionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitShare) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.KeyShare)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TargetHeight)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitShareResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitEncrypted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitEncrypted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitEncrypted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Encryption", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Encryption = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetHeight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetHeight = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deposit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitEncryptedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitEncryptedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitEncryptedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCommitDecryption) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCommitDecryption: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCommitDecryption: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlaintextHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlaintextHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlaintextDecryptorHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlaintextDecryptorHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCommitDecryptionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCommitDecryptionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCommitDecryptionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevealDecryption) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevealDecryption: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevealDecryption: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Plaintext", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Plaintext = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevealDecryptionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevealDecryptionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevealDecryptionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitShare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitShare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitShare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyShare", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyShare = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetHeight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetHeight = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitShareResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitShareResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitShareResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
